apiVersion: v1
kind: Pod
metadata:
  name: nginx-allowed
spec:
  containers:
    - name: nginx
      image: docker.io/nginx
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"