apiVersion: v1
kind: Pod
metadata:
  name: busybox-allowed
spec:
  containers:
    - name: busybox
      image: docker.io/busybox
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"